import { Router } from 'express';
import puppeteer from 'puppeteer';
import fs from 'fs-extra';
import path from 'path';
import Assignment from '../models/Assignment.js';
import Submission from '../models/Submission.js';
import EvaluationRun from '../models/EvaluationRun.js';
import StudentProgress from '../models/StudentProgress.js';
import { autoGenerateDomTests, autoGenerateStyleTests } from '../utils/autoGenerateTests.js';
import { uploadScreenshot } from '../utils/cloudinary.js';
import { buildPage } from '../worker/pageBuilder.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router = Router();

// POST /api/assignments — teacher creates assignment
router.post('/', requireAuth, requireRole('teacher'), async (req, res) => {
  const { title, description, html, css, js, functionalityTests, interactionTests } = req.body;
  if (!title || !html) return res.status(400).json({ error: 'title and html are required' });

  const domTests = autoGenerateDomTests(html);
  const styleTests = autoGenerateStyleTests(html, css || '');

  // functionalityTests: array of behavior contract test cases (teacher-defined)
  // interactionTests:   array of click/type interaction tests (teacher-defined)
  const fnTests = Array.isArray(functionalityTests) ? functionalityTests : [];
  const intTests = Array.isArray(interactionTests) ? interactionTests : [];

  const assignment = await Assignment.create({
    title,
    description: description || '',
    createdBy: req.user.id,
    referenceFiles: { html, css: css || '', js: js || '' },
    evalSpec: { domTests, styleTests, interactionTests: intTests, functionalityTests: fnTests }
  });

  // Capture reference screenshots asynchronously (multiple states)
  let referenceScreenshotUrl = null;
  const referenceScreenshots = [];
  let browser = null;

  try {
    const { filePath } = await buildPage(`baseline-${assignment._id}`, { html, css: css || '', js: js || '' });

    browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });
    const page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 720 });

    await page.setRequestInterception(true);
    page.on('request', (r) => {
      const u = r.url();
      if (u.startsWith('file://') || u.startsWith('data:')) r.continue();
      else r.abort();
    });

    await page.goto(`file://${filePath}`, { waitUntil: 'networkidle0', timeout: 10000 });
    await page.addStyleTag({
      content: '*, *::before, *::after { animation-duration: 0s !important; transition-duration: 0s !important; }'
    });
    await new Promise(r => setTimeout(r, 400));

    // Helper: take a screenshot and push to array
    const capture = async (label) => {
      const buf = await page.screenshot({ type: 'png' });
      const url = await uploadScreenshot(buf, `assignments/${assignment._id}`, label);
      referenceScreenshots.push(url);
      return url;
    };

    // 1. Initial viewport (always taken)
    referenceScreenshotUrl = await capture('reference_1_initial');

    // 2. Check if page is taller than viewport → scroll & capture
    const pageHeight = await page.evaluate(() => document.documentElement.scrollHeight);
    const viewHeight = 720;
    if (pageHeight > viewHeight + 100) {
      // Scroll to 50% of page
      await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight / 2));
      await new Promise(r => setTimeout(r, 200));
      await capture('reference_2_midscroll');

      // Scroll to bottom
      await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
      await new Promise(r => setTimeout(r, 200));
      await capture('reference_3_bottom');

      // Scroll back to top
      await page.evaluate(() => window.scrollTo(0, 0));
    }

    // 3. Detect interactive elements that may reveal new content
    //    (tab/nav buttons, accordion triggers, show-more buttons)
    const interactiveSelectors = [
      'button:not([type="submit"])',
      '[role="tab"]',
      'nav a',
      '.tab', '.nav-item', '.accordion-btn',
    ];

    for (const sel of interactiveSelectors) {
      const elements = await page.$$(sel);
      // Click up to 3 distinct interactive elements to capture different UI states
      let clicked = 0;
      for (const el of elements) {
        if (clicked >= 3) break;
        try {
          const visible = await el.isIntersectingViewport();
          if (!visible) continue;
          await el.click();
          await new Promise(r => setTimeout(r, 350));
          const label = `reference_${referenceScreenshots.length + 1}_interaction`;
          await capture(label);
          clicked++;
        } catch { /* element may have disappeared, skip */ }
      }
      if (clicked > 0) break; // One selector group found interactions, stop
    }

    // Update assignment with all screenshots
    await Assignment.findByIdAndUpdate(assignment._id, {
      referenceScreenshotUrl,
      referenceScreenshots,
      baselineGeneratedAt: new Date()
    });

  } catch (err) {
    console.error('Baseline capture failed:', err.message);
  } finally {
    if (browser) await browser.close();
    await fs.remove(`/tmp/eval-baseline-${assignment._id}`).catch(() => { });
  }

  return res.status(201).json({
    assignmentId: assignment._id,
    title: assignment.title,
    testsGenerated: {
      dom: domTests.length,
      style: styleTests.length,
      functionality: fnTests.length,
      interaction: intTests.length
    },
    referenceScreenshotUrl,
    referenceScreenshots,
    screenshotCount: referenceScreenshots.length
  });
});


// GET /api/assignments — list all active assignments
router.get('/', requireAuth, async (req, res) => {
  const assignments = await Assignment.find({ isActive: true })
    .select('_id title description referenceScreenshotUrl referenceScreenshots createdBy createdAt')
    .sort({ createdAt: -1 });
  return res.json(assignments);
});

// GET /api/assignments/:id — full detail
router.get('/:id', requireAuth, async (req, res) => {
  const assignment = await Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });
  return res.json(assignment);
});

// PATCH /api/assignments/:id — teacher updates functionality/interaction tests
router.patch('/:id', requireAuth, requireRole('teacher'), async (req, res) => {
  const { functionalityTests, interactionTests } = req.body;

  const update = {};
  if (Array.isArray(functionalityTests)) update['evalSpec.functionalityTests'] = functionalityTests;
  if (Array.isArray(interactionTests)) update['evalSpec.interactionTests'] = interactionTests;

  if (Object.keys(update).length === 0)
    return res.status(400).json({ error: 'Nothing to update' });

  const assignment = await Assignment.findByIdAndUpdate(
    req.params.id, { $set: update }, { new: true }
  );
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });

  return res.json({
    assignmentId: assignment._id,
    functionalityTests: assignment.evalSpec.functionalityTests.length,
    interactionTests: assignment.evalSpec.interactionTests.length
  });
});

// DELETE /api/assignments/:id — teacher deletes their own assignment (cascade-cleans submissions + eval runs)
router.delete('/:id', requireAuth, requireRole('teacher'), async (req, res) => {
  const assignment = await Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });

  // Only the teacher who created it may delete it
  const storedBy = assignment.createdBy?.toString().trim();
  const requestBy = req.user.id?.toString().trim();
  console.log('[DELETE] createdBy:', storedBy, ' | req.user.id:', requestBy);
  if (storedBy !== requestBy)
    return res.status(403).json({ error: 'You do not own this assignment', debug: { storedBy, requestBy } });

  // 1. Find all submissions for this assignment
  const submissions = await Submission.find({ assignmentId: req.params.id }).select('submissionId');
  const submissionIds = submissions.map(s => s.submissionId);

  // 2. Delete all EvaluationRun records linked to those submissions
  if (submissionIds.length > 0) {
    await EvaluationRun.deleteMany({ submissionId: { $in: submissionIds } });
  }

  // 3. Delete all Submission records for this assignment
  await Submission.deleteMany({ assignmentId: req.params.id });

  // 4. Soft-delete the assignment (keeps the DB reference but hides it from listings)
  await Assignment.findByIdAndUpdate(req.params.id, { isActive: false });

  return res.json({
    success: true,
    message: 'Assignment and all associated submissions deleted.',
    deletedSubmissions: submissionIds.length
  });
});

// GET /api/assignments/:id/submissions — teacher: best submission per student for this assignment
router.get('/:id/submissions', requireAuth, requireRole('teacher'), async (req, res) => {
  // Pull all StudentProgress records for this assignment (one per student)
  const progressRecords = await StudentProgress.find({ assignmentId: req.params.id });

  if (progressRecords.length === 0) return res.json([]);

  // Collect all best submissionIds
  const bestSubmissionIds = progressRecords
    .filter(p => p.bestSubmissionId)
    .map(p => p.bestSubmissionId);

  // Fetch the actual submissions + eval runs in parallel
  const [submissions, runs] = await Promise.all([
    Submission.find({ submissionId: { $in: bestSubmissionIds } }),
    EvaluationRun.find({ submissionId: { $in: bestSubmissionIds } })
  ]);

  const subMap = Object.fromEntries(submissions.map(s => [s.submissionId, s]));
  const runMap = Object.fromEntries(runs.map(r => [r.submissionId, r]));

  // Build response: one row per student with best score + attempt count
  const results = progressRecords.map(p => {
    const sub = subMap[p.bestSubmissionId];
    const run = runMap[p.bestSubmissionId];
    return {
      submissionId: p.bestSubmissionId,
      studentId: p.studentId,
      status: sub?.status ?? (run ? 'done' : 'pending'),
      submittedAt: sub?.submittedAt ?? null,
      attempts: p.attempts,
      bestScore: p.bestScore,
      completed: p.completed,
      completedAt: p.completedAt,
      result: run || null
    };
  });

  // Sort: completed first, then by bestScore descending
  results.sort((a, b) => {
    if (b.completed !== a.completed) return b.completed ? 1 : -1;
    return b.bestScore - a.bestScore;
  });

  return res.json(results);
});

export default router;
