import { Router } from 'express';
import puppeteer from 'puppeteer';
import fs from 'fs-extra';
import path from 'path';
import Assignment from '../models/Assignment.js';
import Submission from '../models/Submission.js';
import EvaluationRun from '../models/EvaluationRun.js';
import { autoGenerateDomTests, autoGenerateStyleTests } from '../utils/autoGenerateTests.js';
import { uploadScreenshot } from '../utils/cloudinary.js';
import { buildPage } from '../worker/pageBuilder.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router = Router();

// POST /api/assignments — teacher creates assignment
router.post('/', requireAuth, requireRole('teacher'), async (req, res) => {
  const { title, description, html, css, js } = req.body;
  if (!title || !html) return res.status(400).json({ error: 'title and html are required' });

  const domTests   = autoGenerateDomTests(html);
  const styleTests = autoGenerateStyleTests(html, css || '');

  const assignment = await Assignment.create({
    title,
    description: description || '',
    createdBy: req.user.id,
    referenceFiles: { html, css: css || '', js: js || '' },
    evalSpec: { domTests, styleTests, interactionTests: [] }
  });

  // Capture reference screenshot asynchronously
  let referenceScreenshotUrl = null;
  const tempDir = `/tmp/baseline-${assignment._id}`;
  let browser = null;

  try {
    const { filePath } = await buildPage(`baseline-${assignment._id}`, { html, css: css || '', js: js || '' });

    browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });
    const page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 720 });

    await page.setRequestInterception(true);
    page.on('request', (r) => {
      const u = r.url();
      if (u.startsWith('file://') || u.startsWith('data:')) r.continue();
      else r.abort();
    });

    await page.goto(`file://${filePath}`, { waitUntil: 'networkidle0', timeout: 10000 });
    await page.addStyleTag({
      content: '*, *::before, *::after { animation-duration: 0s !important; transition-duration: 0s !important; }'
    });
    await new Promise(r => setTimeout(r, 400));

    const screenshotBuffer = await page.screenshot({ type: 'png' });

    referenceScreenshotUrl = await uploadScreenshot(
      screenshotBuffer,
      `assignments/${assignment._id}`,
      'reference'
    );

    await Assignment.findByIdAndUpdate(assignment._id, {
      referenceScreenshotUrl,
      baselineGeneratedAt: new Date()
    });
  } catch (err) {
    console.error('Baseline capture failed:', err.message);
  } finally {
    if (browser) await browser.close();
    await fs.remove(tempDir).catch(() => {});
    // Also clean up the temp file from buildPage
    await fs.remove(`/tmp/eval-baseline-${assignment._id}`).catch(() => {});
  }

  return res.status(201).json({
    assignmentId: assignment._id,
    title: assignment.title,
    testsGenerated: { dom: domTests.length, style: styleTests.length },
    referenceScreenshotUrl
  });
});

// GET /api/assignments — list all active assignments
router.get('/', requireAuth, async (req, res) => {
  const assignments = await Assignment.find({ isActive: true })
    .select('_id title description referenceScreenshotUrl createdBy createdAt')
    .sort({ createdAt: -1 });
  return res.json(assignments);
});

// GET /api/assignments/:id — full detail
router.get('/:id', requireAuth, async (req, res) => {
  const assignment = await Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });
  return res.json(assignment);
});

// GET /api/assignments/:id/submissions — teacher: all submissions + results for this assignment
router.get('/:id/submissions', requireAuth, requireRole('teacher'), async (req, res) => {
  const submissions = await Submission.find({ assignmentId: req.params.id })
    .sort({ submittedAt: -1 });

  const submissionIds = submissions.map(s => s.submissionId);
  const runs = await EvaluationRun.find({ submissionId: { $in: submissionIds } });
  const runMap = Object.fromEntries(runs.map(r => [r.submissionId, r]));

  const results = submissions.map(s => ({
    submissionId: s.submissionId,
    studentId: s.studentId,
    status: s.status,
    submittedAt: s.submittedAt,
    result: runMap[s.submissionId] || null
  }));

  return res.json(results);
});

export default router;
