import { parse } from 'node-html-parser';

export function autoGenerateDomTests(htmlString) {
  const root = parse(htmlString);
  const tests = [];
  let idCounter = 1;
  const seen = new Set();

  function addTest(test) {
    const key = `${test.selector}|${test.assert}|${test.textContains || ''}`;
    if (seen.has(key)) return;
    seen.add(key);
    tests.push({ id: `dom-${idCounter++}`, ...test });
  }

  // 1. Elements with IDs
  root.querySelectorAll('[id]').forEach(el => {
    const id = el.getAttribute('id');
    if (!id) return;
    addTest({ name: `#${id} exists`, selector: `#${id}`, assert: 'exists', weight: 10 });
  });

  // 2. Headings with text
  ['h1', 'h2', 'h3'].forEach(tag => {
    root.querySelectorAll(tag).forEach(el => {
      const text = el.text.trim();
      if (!text) return;
      addTest({ name: `${tag} contains "${text}"`, selector: tag, assert: 'textContains', textContains: text, weight: 10 });
    });
  });

  // 3. Buttons
  root.querySelectorAll('button, input[type="submit"], input[type="button"]').forEach(el => {
    const id = el.getAttribute('id');
    const label = el.text.trim() || el.getAttribute('value') || id || 'button';
    const selector = id ? `#${id}` : 'button';
    addTest({ name: `Button "${label}" exists`, selector, assert: 'exists', weight: 10 });
  });

  // 4. Forms
  root.querySelectorAll('form').forEach(el => {
    const id = el.getAttribute('id');
    const selector = id ? `#${id}` : 'form';
    addTest({ name: `Form ${id ? `#${id}` : ''} exists`.trim(), selector, assert: 'exists', weight: 10 });
  });

  // 5. Radio inputs by value
  root.querySelectorAll('input[type="radio"]').forEach(el => {
    const value = el.getAttribute('value');
    if (!value) return;
    addTest({ name: `Radio input value="${value}" exists`, selector: `input[type="radio"][value="${value}"]`, assert: 'exists', weight: 5 });
  });

  // 6. Semantic classes
  ['box', 'card', 'container', 'title', 'header', 'footer', 'nav', 'wrapper', 'content', 'main'].forEach(cls => {
    if (!root.querySelector(`.${cls}`)) return;
    addTest({ name: `.${cls} exists`, selector: `.${cls}`, assert: 'exists', weight: 5 });
  });

  // 7. Images with alt
  root.querySelectorAll('img[alt]').forEach(el => {
    const alt = el.getAttribute('alt');
    if (!alt) return;
    addTest({ name: `img[alt="${alt}"] exists`, selector: `img[alt="${alt}"]`, assert: 'exists', weight: 5 });
  });

  return tests;
}

export function autoGenerateStyleTests(htmlString, cssString) {
  const root = parse(htmlString);
  const tests = [];
  let idCounter = 1;
  const seen = new Set();

  function addTest(test) {
    const key = `${test.selector}|${test.property}`;
    if (seen.has(key)) return;
    seen.add(key);
    tests.push({ id: `css-${idCounter++}`, ...test });
  }

  // display: flex on body
  if (/body\s*\{[^}]*display\s*:\s*flex/s.test(cssString)) {
    addTest({ name: 'body has display:flex', selector: 'body', property: 'display', expect: 'flex', weight: 20 });
  }

  // display: grid — find the selector
  const gridMatch = cssString.match(/([.#][\w-]+)\s*\{[^}]*display\s*:\s*grid/s);
  if (gridMatch) {
    const sel = gridMatch[1];
    if (root.querySelector(sel)) {
      addTest({ name: `${sel} has display:grid`, selector: sel, property: 'display', expect: 'grid', weight: 20 });
    }
  }

  // border-radius on .box or .card
  ['.box', '.card'].forEach(cls => {
    if (!root.querySelector(cls)) return;
    const clsName = cls.replace('.', '');
    if (new RegExp(`\\.${clsName}\\s*\\{[^}]*border-radius`, 's').test(cssString)) {
      addTest({ name: `${cls} has border-radius`, selector: cls, property: 'border-radius', expect: 'notZero', weight: 15 });
    }
  });

  // background-color on #submit or .btn
  const btnEl = root.querySelector('#submit') || root.querySelector('button[type="submit"]') || root.querySelector('.btn');
  if (btnEl) {
    const sel = btnEl.getAttribute('id') ? `#${btnEl.getAttribute('id')}` : 'button';
    if (cssString.includes('background') || cssString.includes('background-color')) {
      addTest({ name: `${sel} has background-color`, selector: sel, property: 'background-color', expect: 'notDefault', weight: 20 });
    }
  }

  // min-height on body
  if (/body\s*\{[^}]*min-height/s.test(cssString)) {
    addTest({ name: 'body has min-height', selector: 'body', property: 'min-height', expect: 'notZero', weight: 15 });
  }

  // max-width on .box or .card or .container
  ['.box', '.card', '.container'].forEach(cls => {
    if (!root.querySelector(cls)) return;
    const clsName = cls.replace('.', '');
    if (new RegExp(`\\.${clsName}\\s*\\{[^}]*max-width`, 's').test(cssString)) {
      addTest({ name: `${cls} has max-width`, selector: cls, property: 'max-width', expect: 'notNone', weight: 10 });
    }
  });

  return tests;
}
